create database PruTec

use PruTec

CREATE TABLE [dbo].[CARROS](
    [Id] [int] IDENTITY(1,1) NOT NULL,
    [MODELO] [nvarchar](200) NULL,
    [COLOR] [nvarchar](200) NULL,
    [KILOMETRAJE] [int] NULL,
	[VALOR] [int] NULL,
	[IMAGEN] [nvarchar](max) NULL,
	[FECHA_REGISTRO] [DATE] NULL,
	[TIPO] [nvarchar](200) NULL,
CONSTRAINT [PK_Carros] PRIMARY KEY CLUSTERED 
(
    [Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[MOTOS](
    [Id] [int] IDENTITY(1,1) NOT NULL,
    [MODELO] [nvarchar](200) NULL,
    [COLOR] [nvarchar](200) NULL,
    [KILOMETRAJE] [int] NULL,
	[VALOR] [int] NULL,
	[IMAGEN] [nvarchar](max) NULL,
	[FECHA_REGISTRO] [DATE] NULL,
	[TIPO] [nvarchar](200) NULL,
	[CILINDRAJE] [int] NULL,
	[VELOCIDADES] [int] NULL,
CONSTRAINT [PK_MOTOS] PRIMARY KEY CLUSTERED 
(
    [Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[VENTAS](
    [Id] [int] IDENTITY(1,1) NOT NULL,
    [NOMBRE] [nvarchar](200) NULL,
    [DOCUMENTO] [nvarchar](200) NULL,
	[FECHA_REGISTRO] [DATE] NULL,
CONSTRAINT [PK_VENTAS] PRIMARY KEY CLUSTERED 
(
    [Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
